name: Feature/Improvement request
description: Suggest an idea for Asterisk
title: title
labels: feature-request
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature or improvement request related to a problem? Please describe.
      value: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      value: |
        A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      value: |
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      value: |
        Add any other context or screenshots about the feature request here.
  - type: markdown
    attributes:
      value: |
        Please consider posting your request to the [Asterisk Forums Jobs section](https://community.asterisk.org/c/jobs/) and/or kindly reviewing the [Asterisk Bug Bounties documentation](https://docs.asterisk.org/Development/Asterisk-Bug-Bounties/).
